# https://github.com/stefanzweifel/git-auto-commit-action/issues/163            
# Workaround to address GitHub Token behavior
# Commits made using the GitHub token (e.g., merge and version bump) do not trigger workflows by default.
# GitHub status checks that control the merge button's availability only evaluate the latest commit's status.
# Since the latest commits (merge and version bump) were made with the GitHub token, these status checks remain untriggered.
# Therefore, we manually update the status to ensure the merge button is enabled.

name: Update commit status

inputs:
    CONTEXT:
      required: true
      type: string
    GITHUB_TOKEN:
      required: true
      type: string
    STATE:
      required: true
      type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        clean: false
    - name: Update commit status
      shell: bash
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_HASH \
          -d '{"state":"${{ inputs.STATE }}","context":"${{ inputs.CONTEXT }}"}'