name: Ready for merge

on:
  workflow_call:
    
jobs: 
  sync_with_main_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Get latest changes from main
        run: git pull origin main --rebase

      - name: Install modules and cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore npm cache
        run: npm ci

      - name: Build and run tests
        run: |
          npm run build
          npm run test