name: Stage/Beta arm server

on:
  workflow_call:
    secrets:
      VAULT:
        required: true
    inputs:
      AWS_ACCOUNT:
        required: true
        type: string
      TARGET:
        required: true
        type: string
      DOMAIN:
        required: true
        type: string
      NODE_ENV:
        required: true
        type: string
      VAULT_CMD:
        required: true
        type: string
      HELLO_SVR:
        required: true
        type: string

jobs:
  stage:
    runs-on: hello_arm
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build role name and set AWS_REGION
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          ROLE_NAME="arn:aws:iam::${{ inputs.AWS_ACCOUNT }}:role/${REPO_NAME}-repo"
          echo "ROLE_NAME=${ROLE_NAME}" >> $GITHUB_ENV
          echo "AWS_REGION=us-west-2" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "ROLE_NAME=${{ env.ROLE_NAME }}"
          echo "AWS_REGION=${{ env.AWS_REGION }}"
          echo "HELLO_VERSION=${{ env.HELLO_VERSION }}"
          echo "GIT_COMMIT=${{ env.GIT_COMMIT }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_NAME }}
          aws-region: us-west-2

      - name: Check if ECR Repository Exists
        run: |
          if aws ecr describe-repositories --repository-names hello-${{ inputs.HELLO_SVR }}-arm > /dev/null 2>&1; then
            echo "Repository exists."
          else
            echo "Repository does not exist. Exiting."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.TARGET }}

      - name: Get HELLO_VERSION
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "HELLO_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Debug HELLO_VERSION
        run: echo "HELLO_VERSION=${{ env.HELLO_VERSION }}"

      - name: Set GIT_COMMIT to ENV
        run: |
          GIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})
          echo "GIT_COMMIT=${GIT_SHA_SHORT}" >> $GITHUB_ENV

      - name: Set Repo Vars
        run: |
          IMAGE=hello-${{ inputs.HELLO_SVR }}-arm
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          ECR=${{ inputs.AWS_ACCOUNT }}.dkr.ecr.${AWS_REGION}.amazonaws.com
          echo "ECR=${ECR}" >> $GITHUB_ENV
          REPO_ARN=${ECR}/${IMAGE}
          echo "REPO_ARN=${REPO_ARN}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "AWS_REGION=${AWS_REGION}"
          echo "HELLO_VERSION=${HELLO_VERSION}"
          echo "GIT_COMMIT=${GIT_COMMIT}"
          echo "IMAGE=${IMAGE}"
          echo "ECR=${ECR}"
          echo "REPO_ARN=${REPO_ARN}"

      - name: Login to Docker
        run: |
          aws ecr get-login-password --region ${AWS_REGION} | \
          docker login --username AWS --password-stdin ${ECR}
  
  
      # - name: Build Image
      #   run: |
      #     docker build -t hello-wallet-arm:prod svr
      #     docker tag hello-wallet-arm:prod 448617543178.dkr.ecr.us-west-2.amazonaws.com/hello-wallet-arm:prod
      
      # - name: Push Image to ECR
      #   run: |
      #     docker push 448617543178.dkr.ecr.us-west-2.amazonaws.com/hello-wallet-arm:prod

      - uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: svr
          push: false # docker/build-push-action@v5 does not work with push to ECR
          tags: ${{ env.IMAGE }}:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            HELLO_VERSION=${{ env.HELLO_VERSION }}
            GIT_COMMIT=${{ env.GIT_COMMIT }}
      
      - name: Push Image to ECR
        run: |
          docker tag ${IMAGE}:prod ${REPO_ARN}:prod
          docker tag ${IMAGE}:prod ${REPO_ARN}:${HELLO_VERSION}
          docker tag ${IMAGE}:prod ${REPO_ARN}:${GIT_COMMIT}
          docker push ${REPO_ARN}:prod
          docker push ${REPO_ARN}:${HELLO_VERSION}
          docker push ${REPO_ARN}:${GIT_COMMIT}

      - name: Restart ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ inputs.HELLO_SVR }}-arm \
            --service ${{ inputs.HELLO_SVR }}-arm \
            --force-new-deployment