name: Test ARM

on:
  workflow_call:
    
jobs: 
  test_arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
          
      - name: Install modules and cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore npm cache
        run: npm ci

      - name: Build and run tests
        run: |
          npm run build
